# Generated by Django 3.2.24 on 2024-03-02 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0006_auto_20240301_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AddField(
            model_name='group',
            name='student',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Студент'),
        ),
    ]
